@echo off 
REM === Auto-generated script to recreate folder structure and placeholder files === 
 
mkdir "JobAgentBotV2\project_root" 
mkdir "JobAgentBotV2\project_root\core" 
mkdir "JobAgentBotV2\project_root\logs" 
mkdir "JobAgentBotV2\project_root\modules" 
mkdir "JobAgentBotV2\project_root\output" 
mkdir "JobAgentBotV2\project_root\outputs" 
mkdir "JobAgentBotV2\project_root\tests" 
mkdir "JobAgentBotV2\project_root\core\config" 
mkdir "JobAgentBotV2\project_root\core\utils" 
mkdir "JobAgentBotV2\project_root\modules\email_link_extractor" 
mkdir "JobAgentBotV2\project_root\modules\email_reader" 
mkdir "JobAgentBotV2\project_root\modules\job_portal_automation" 
mkdir "JobAgentBotV2\project_root\modules\resume_matching" 
type nul > "JobAgentBotV2\project_root\checkpoint.txt" 
type nul > "JobAgentBotV2\project_root\create_init_files.py" 
type nul > "JobAgentBotV2\project_root\main.py" 
type nul > "JobAgentBotV2\project_root\README.md" 
type nul > "JobAgentBotV2\project_root\requirements.txt" 
type nul > "JobAgentBotV2\project_root\__init__.py" 
type nul > "JobAgentBotV2\project_root\core\__init__.py" 
type nul > "JobAgentBotV2\project_root\core\config\config.env" 
type nul > "JobAgentBotV2\project_root\core\config\__init__.py" 
type nul > "JobAgentBotV2\project_root\core\utils\config_loader.py" 
type nul > "JobAgentBotV2\project_root\core\utils\logger_config.py" 
type nul > "JobAgentBotV2\project_root\core\utils\__init__.py" 
type nul > "JobAgentBotV2\project_root\logs\__init__.py" 
type nul > "JobAgentBotV2\project_root\modules\__init__.py" 
type nul > "JobAgentBotV2\project_root\modules\email_link_extractor\link_extractor.py" 
type nul > "JobAgentBotV2\project_root\modules\email_link_extractor\__init__.py" 
type nul > "JobAgentBotV2\project_root\modules\email_reader\.env" 
type nul > "JobAgentBotV2\project_root\modules\email_reader\email_reader.py" 
type nul > "JobAgentBotV2\project_root\modules\email_reader\email_readerv2.py" 
type nul > "JobAgentBotV2\project_root\modules\email_reader\__init__.py" 
type nul > "JobAgentBotV2\project_root\modules\job_portal_automation\job_portal_bot.py" 
type nul > "JobAgentBotV2\project_root\modules\job_portal_automation\__init__.py" 
type nul > "JobAgentBotV2\project_root\modules\resume_matching\resume_matcher.py" 
type nul > "JobAgentBotV2\project_root\modules\resume_matching\__init__.py" 
type nul > "JobAgentBotV2\project_root\outputs\__init__.py" 
type nul > "JobAgentBotV2\project_root\tests\test_config_loader.py" 
type nul > "JobAgentBotV2\project_root\tests\test_link_extractor.py" 
type nul > "JobAgentBotV2\project_root\tests\test_logger.py" 
type nul > "JobAgentBotV2\project_root\tests\test_logger_config.py" 
type nul > "JobAgentBotV2\project_root\tests\__init__.py" 
 
echo Structure recreated successfully. 
pause 
